env: pybullet.TableEnv
env_kwargs:
  name: rearrangement_push_0
  gui: false

  primitives:
    - pick
    - place
    - pull
    - push

  tasks:
    - action_skeleton:
        - pick(blue_box, table)
        - place(blue_box, table)
        - pick(hook, table)
        - push(cyan_box, hook, rack)
      initial_state:
        - free(hook)
        - free(blue_box)
        - free(cyan_box)
        - aligned(rack)
        - poslimit(rack)
        - inworkspace(hook)
        - inoperationalzone(cyan_box)
        - inobstructionzone(blue_box)
        - beyondworkspace(rack)
        - infront(blue_box, rack)
        - infront(cyan_box, rack)
        - on(rack, table)
        - on(hook, table)
        - on(blue_box, table)
        - on(cyan_box, table)
        
  robot_config: configs/pybullet/envs/robots/franka_panda_sim.yaml

  objects:
    - object_type: Urdf
      object_kwargs:
        name: table
        path: configs/pybullet/envs/assets/iprl_table.urdf
        is_static: true
    - object_type: Rack
      object_kwargs:
        name: rack
        size: [0.22, 0.32, 0.16]
        color: [0.4, 0.2, 0.0, 1.0]
    - object_type: Hook
      object_kwargs:
        name: hook
        head_length: 0.2
        handle_length: 0.38
        handle_y: -1.0
        color: [0.6, 0.6, 0.6, 1.0]
    - object_type: Box
      object_kwargs:
        name: blue_box
        size: [0.08, 0.05, 0.07]
        color: [0.0, 0.0, 1.0, 1.0]
    - object_type: Box
      object_kwargs:
        name: cyan_box
        size: [0.06, 0.03, 0.06]
        color: [0.0, 1.0, 1.0, 1.0]
