name: temporal_policies

channels:
  - pytorch
  - conda-forge
  - default

dependencies:
  - python=3.7
  
  # PyTorch
  - pytorch
  - cpuonly
  - torchvision
  - torchtext

  # NumPy Family
  - numpy
  - scipy
  - networkx
  - scikit-image

  # Env
  - pybox2d

  # IO
  - imageio
  - pillow
  - pyyaml
  - cloudpickle
  - h5py
  - absl-py
  - pyparsing

  # Plotting
  - tensorboard
  - pandas
  - matplotlib
  - seaborn

  # Other
  - pytest
  - tqdm
  - future

  - pip
  - pip:
      - -r requirements.txt