encoder: VAE
encoder_kwargs:
  encoder_class: encoders.ConvEncoder
  encoder_kwargs:
    latent_dim: 128
    # hidden_channels: [16, 32, 64, 128, 256]  # (32, 16, 8, 4, 2)
    hidden_channels: [32, 32, 64, 64, 512]  # (32, 16, 8, 4, 2)

  decoder_class: encoders.ConvDecoder
  decoder_kwargs:
    latent_dim: 128
    # hidden_channels: [256, 128, 64, 32, 16]  # (2, 4, 8, 16, 32)
    hidden_channels: [512, 64, 64, 32, 32]  # (2, 4, 8, 16, 32)

  beta: 1.0
  kl_reset_steps: 10000
  kl_warmup_steps: 5000
  anneal_beta: true
  anneal_gamma: false
